[pytest]
addopts = --cov=src --cov-report=html --cov-report=term-missing
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:datetime.datetime.utcnow() is deprecated:DeprecationWarning
    ignore::DeprecationWarning:openpyxl.*
