exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist",
    "vulture_whitelist.py",
]

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = ["E501", "C901"] # Ignora "line too long" e complessità ciclomatica eccessiva

[format]
quote-style = "double"
