# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources.qrc'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore

qt_resource_data = b'''
<RCC version="1.0">
<qresource>
    <file alias="icons/play.svg">assets/icons/play.svg</file>
    <file alias="icons/stop.svg">assets/icons/stop.svg</file>
</qresource>
</RCC>
'''

qt_resource_name = b'resources'

qt_resource_struct = b"""
<RCC version="1.0">
    <qresource prefix="/">
        <file alias="icons/play.svg">assets/icons/play.svg</file>
        <file alias="icons/stop.svg">assets/icons/stop.svg</file>
    </qresource>
</RCC>
"""

def qInitResources():
    QtCore.qRegisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)

def qCleanupResources():
    QtCore.qUnregisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)

qInitResources()
