import sqlite3
import pytest
import os
from unittest.mock import patch, MagicMock
from datetime import datetime, timedelta
from src.core.audit_manager import AuditManager

class TestAuditManager:
    """Test suite for AuditManager in src/core/audit_manager.py"""

    @pytest.fixture
    def mock_db(self, tmp_path):
        """Creates a temporary DB for AuditManager."""
        db_file = tmp_path / "test_audit.db"
        
        # Patch the class-level DB_PATH
        with patch("src.core.audit_manager.AuditManager.DB_PATH", db_file):
            # Reset instance to ensure __init_db__ runs on new DB
            AuditManager._instance = None
            manager = AuditManager()
            yield manager
            
            # Cleanup
            AuditManager._instance = None

    def test_singleton(self, mock_db):
        m1 = AuditManager()
        m2 = AuditManager()
        assert m1 is m2

    def test_init_db_creates_table(self, mock_db):
        assert mock_db.DB_PATH.exists()
        with sqlite3.connect(mock_db.DB_PATH) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='audit_logs'")
            assert cursor.fetchone() is not None

    def test_log_action_success(self, mock_db):
        mock_db.log_action("Test Action", category="TEST", entity="Item1")
        
        logs = mock_db.get_logs()
        assert len(logs) == 1
        entry = logs[0]
        assert entry["action"] == "Test Action"
        assert entry["category"] == "TEST"
        assert entry["status"] == "success"
        # Verify hash was generated
        assert entry["row_hash"] is not None

    def test_integrity_verification_valid(self, mock_db):
        mock_db.log_action("A1")
        mock_db.log_action("A2")
        
        assert mock_db.verify_integrity() is True

    def test_integrity_verification_tampered(self, mock_db):
        mock_db.log_action("A1")
        
        # Tamper DB manually
        with sqlite3.connect(mock_db.DB_PATH) as conn:
            conn.execute("UPDATE audit_logs SET action='HACKED' WHERE id=1")
            conn.commit()
            
        assert mock_db.verify_integrity() is False

    def test_retention_policy(self, mock_db):
        # Insert old record (using SQL directly to bypass timestamp auto-set)
        old_date = (datetime.now() - timedelta(days=100)).isoformat()
        with sqlite3.connect(mock_db.DB_PATH) as conn:
            conn.execute(
                "INSERT INTO audit_logs (timestamp, action, row_hash) VALUES (?, ?, ?)",
                (old_date, "OLD", "hash")
            )
            conn.commit()
            
        mock_db.run_retention_policy(days=90)
        
        logs = mock_db.get_logs()
        # Should contain only the "Retention Policy" log created by the method itself
        # The OLD one should be gone.
        actions = [l["action"] for l in logs]
        assert "OLD" not in actions
        assert "Sistema" in actions # The log generated by run_retention_policy

    def test_notification_trigger(self, mock_db):
        """Test that notification manager is called if notify=True."""
        with patch("src.core.notification_manager.NotificationManager.instance") as mock_nm:
            mock_instance = mock_nm.return_value
            
            # Case 1: Error status
            mock_db.log_action("NotifyMe", notify=True, status=AuditManager.Status.ERROR)
            assert mock_instance.add_notification.call_args[1]["level"] == "error"
            
            # Case 2: Warning status
            mock_db.log_action("NotifyWarn", notify=True, status=AuditManager.Status.WARNING)
            assert mock_instance.add_notification.call_args[1]["level"] == "warning"
            
            # Case 3: Success with custom params (nuova)
            mock_db.log_action("Update", notify=True, params={"nuova": "2.0.0"})
            assert "Versione aggiornata a 2.0.0" in mock_instance.add_notification.call_args[0][1]

            # Case 4: Success with custom params (righe)
            mock_db.log_action("Import", notify=True, params={"righe": 100})
            assert "Elaborate 100 righe" in mock_instance.add_notification.call_args[0][1]

    @patch("src.core.audit_manager.os.environ.get")
    def test_get_current_user_fallbacks(self, mock_env, mock_db):
        """Test user fallbacks when environment is missing."""
        mock_env.return_value = None # No USERNAME/USER
        
        # Test getpass fallback
        with patch("getpass.getuser", return_value="GetPassUser"):
            assert mock_db._get_current_user() == "GetPassUser"
            
        # Test unknown fallback
        with patch("getpass.getuser", side_effect=Exception("Failed")):
            # If win32 check fails too
            with patch("src.core.audit_manager.os.name", "posix"):
                assert mock_db._get_current_user() == "unknown"

    @pytest.mark.skipif(os.name != "nt", reason="Windows specific test")
    @patch("src.core.audit_manager.os.environ.get")
    def test_get_current_user_win32(self, mock_env, mock_db):
        """Test Windows API fallback."""
        mock_env.return_value = None
        with patch("getpass.getuser", side_effect=Exception("Failed")):
            # This should trigger the win32 code path
            user = mock_db._get_current_user()
            assert user != "unknown"

    def test_integrity_legacy_records(self, mock_db):
        """Test that integrity skips legacy records without hash."""
        with sqlite3.connect(mock_db.DB_PATH) as conn:
            # Insert record without hash
            conn.execute(
                "INSERT INTO audit_logs (timestamp, action, row_hash) VALUES (?, ?, ?)",
                (datetime.now().isoformat(), "LEGACY", None)
            )
            conn.commit()
            
        assert mock_db.verify_integrity() is True

    def test_get_logs_exception(self, mock_db):
        """Test get_logs error handling."""
        with patch("src.core.audit_manager.sqlite3.connect", side_effect=sqlite3.Error("Query Fail")):
            assert mock_db.get_logs() == []

    def test_run_retention_policy_exception(self, mock_db):
        """Test run_retention_policy error handling."""
        with patch("src.core.audit_manager.sqlite3.connect", side_effect=sqlite3.Error("Delete Fail")):
            # Should not crash
            mock_db.run_retention_policy()

    def test_get_last_hash_exception(self, mock_db):
        """Test _get_last_hash exception handling."""
        with patch("src.core.audit_manager.sqlite3.connect", side_effect=Exception("Hash Fail")):
            assert mock_db._get_last_hash() == "0" * 64

    def test_verify_integrity_exception(self, mock_db):
        """Test verify_integrity exception handling."""
        with patch("src.core.audit_manager.sqlite3.connect", side_effect=Exception("Integrity Fail")):
            assert mock_db.verify_integrity() is False
