name: Nuitka Build Pipeline

on:
  # push:
  #   branches: [ feat/nuitka-compilation ]
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    name: Build with Nuitka (Windows)
    runs-on: windows-2025
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install Poetry & Dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install uv
                        uv sync --with dev

    - name: Build with Nuitka
      shell: pwsh
      run: |
        $env:PYTHONUTF8=1
        uv run python "devtools/gui/Crea Setup/build_dist.py" --use-nuitka --no-deploy --no-network

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: SyncroJob-Installer-Nuitka
        path: "devtools/gui/Crea Setup/Setup/*.exe"
        if-no-files-found: error

# Fix Path & Poetry v1.1
